# Generated by Django 4.2.9 on 2024-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0002_role_userrole_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
