# Generated by Django 4.2.7 on 2023-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider1_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
