# Generated by Django 4.2.5 on 2023-12-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider1_api', '0002_provider_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='kubeconfig_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
