# Generated by Django 4.2.5 on 2023-11-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_remove_dbcredentials_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBcredentials',
            new_name='DBcredentials1',
        ),
    ]
