# Generated by Django 4.2.5 on 2023-11-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_rename_dbcredentials_dbcredentials1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBcredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterName', models.CharField(max_length=225)),
                ('pipeline_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
