# Generated by Django 4.2.5 on 2023-11-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0005_dbcredentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBcredentials1',
        ),
    ]
