# Generated by Django 4.2.9 on 2024-01-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0006_delete_dbcredentials1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='host_ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
