# Generated by Django 4.2.9 on 2024-01-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0007_cluster_host_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='host_ip',
        ),
        migrations.AddField(
            model_name='cluster',
            name='clusterName',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='pipeline_id',
            field=models.IntegerField(null=True),
        ),
    ]
