# Generated by Django 4.2.9 on 2024-01-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0008_remove_cluster_host_ip_cluster_clustername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='clusterName',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='pipeline_id',
        ),
    ]
