# Generated by Django 4.2.9 on 2024-01-31 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_api', '0009_remove_cluster_clustername_remove_cluster_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=225)),
                ('cluster_type', models.CharField(max_length=225)),
                ('database_version', models.CharField(max_length=225)),
                ('provider_name', models.CharField(max_length=225)),
                ('pipeline_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('dbcredentials'), models.Model),
        ),
    ]
